apiVersion: apps/v1
kind: Deployment
metadata:
  name: flarie-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flarie-todo
  template:
    metadata:
      labels:
        app: flarie-todo
    spec:
      containers:
      - name: flarie-todo
        image: mehedihub/flarie-todo:latest
        ports:
        - containerPort: 3000
